### ISSUE TITLE
download_timeseries should support multi vars

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/powstreams#19]
like `load_timeseries` does. Requires some wizardry, but should follow the same user expectation.

**Comment by aappling-usgs** [comment]
this is basically https://github.com/USGS-R/mda.streams/issues/61. looks like the infrastructure for this is better within powstreams at this point

**Comment by aappling-usgs** [comment]
could allow the user to specify the join function - inner_join, full_join, and left_join could all make sense for progressive binding of the ts variables named by the `variable` vector.

**Comment by aappling-usgs** [comment]
What does that look like for `download_timeseries` to support multiple variables? Is it the same as `load_timeseries()` followed by `write.csv()`? Or does it download all listed ts variables but keep them in their separate files?

**Comment by jread-usgs** [comment]
I was thinking these would be separate, unless (maybe??) a merge argument was used as optional? Not sure though. Having trouble thinking of this usage pattern. I know what I want from `load_timeseries` for multivars (a merged data.frame), but I don't know that it also maps for `download`.

**Comment by aappling-usgs** [comment]
`mda.streams::download_ts` now does this. `download_timeseries` is obsolete.
