### ISSUE TITLE
identify sites by name

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/powstreams#27]
Is there a way to search in our database for sites that match a particular name (e.g., French Broad) and/or to find the name of a site from its site ID?

**Comment by jread-usgs** [comment]
Not at present, but probably something `dataRetrieval` might be able to do? @ldecicco-USGS

**Comment by ldecicco-USGS** [comment]
Fun river!

**Comment by ldecicco-USGS** [comment]
Oh, and, you can definitely get the name from the site id:

```r
library(dataRetrieval)
sites <- readNWISsite(c('05114000','09423350'))
sites$station_nm
[1] "SOURIS RIVER NR SHERWOOD, ND" "CARUTHERS C NR IVANPAH CA" 
```

You can't query directly by station name. So, you can figure out a way to get a set of sites, then search from there (so, maybe North Carolina, or a bounding box, or huc):

```r
siteInfo <- readNWISdata(stateCd="NC", parameterCd="00060",
                         hasDataTypeCd="iv", service="site")
fbSites <- siteInfo[grep("FRENCH", siteInfo$station_nm),]
head(fbSites[,1:3])
    agency_cd  site_no                            station_nm
194      USGS 03439000      FRENCH BROAD RIVER AT ROSMAN, NC
196      USGS 03443000    FRENCH BROAD RIVER AT BLANTYRE, NC
198      USGS 03447687  FRENCH BROAD RIVER NEAR FLETCHER, NC
202      USGS 03451500   FRENCH BROAD RIVER AT ASHEVILLE, NC
204      USGS 03453500    FRENCH BROAD RIVER AT MARSHALL, NC
205      USGS 03454500 FRENCH BROAD RIVER AT HOT SPRINGS, NC
```

**Comment by aappling-usgs** [comment]
Great! Thanks.

**Comment by aappling-usgs** [comment]
this should be done first in mda.streams, then ported here. see https://github.com/USGS-R/mda.streams/issues/122
