### ISSUE TITLE
import useful functions from mda.streams

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/powstreams#36]
wrap anything useful to collaborators from mda.streams. consider renaming for clarity where appropriate. the list of exported functions in `powstreams` should be tidy and full of only those functions we expect collaborators might want to use (e.g., not stage, post, or delete anything except maybe presentations & publications).

**Comment by jread-usgs** [comment]
- [ ] find_google_map
- [ ] find_site_coords
- [ ] others?

**Comment by aappling-usgs** [comment]
maybe some/all of these?
[ ] combine_ts (for combining independent ts vars into one table)
[ ] get_meta (maybe renamed. this is how you can get tables of site data, assuming we get e.g. Mike's data onto SB in time)
[ ] locate_site / locate_ts (optional, but might be demystifying if they can see the data on SB. browser option is fun)
[ ] summarize_ts (we could also think about additional summary variables to include)

**Comment by aappling-usgs** [comment]
this is how dplyr imports %>% (https://github.com/hadley/dplyr/blob/50309db8f04cbcc87e4568a4bfa1f0c718e824c9/R/chain.r#L102):
```r
#' @importFrom magrittr %>%
#' @name %>%
#' @export
#' @rdname chain
#' @usage lhs \%>\% rhs
NULL
```
(and that's it!)

might be a good approach for us, too

**Comment by aappling-usgs** [comment]
got a bunch in there
