### ISSUE TITLE
incorporate UI fully into package

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/powstreams#39]
hoping for functions (maybe `explore_map` and `explore_timeseries`) to launch the powstreamsUI shiny apps. looks like option 2 here might work: http://www.r-bloggers.com/supplementing-your-r-package-with-a-shiny-app/

also wondering if we can jet the powstreamsUI.Rproj file.

**Comment by jread-usgs** [comment]
yes to both. I'm on it. I was working to get to the functionality, now time for some housekeeping.

**Comment by aappling-usgs** [comment]
:+1:
