### ISSUE TITLE
load_timeseries should use combine_ts

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/powstreams#42]
because i put a lot of work into mda.streams::combine_ts, and it's cool and more flexible and works better with unitted timeserieses

**Comment by jread-usgs** [comment]
where are you thinking this should be worked in? to the multi-var load_timeseries?

**Comment by aappling-usgs** [comment]
yeah. basically in place of join.fun

**Comment by aappling-usgs** [comment]
(but combine_ts can combine a bunch of tables all at once, so we could first load a list of tses and then run combine_ts just once)

**Comment by jread-usgs** [comment]
ok, am working on https://trello.com/c/pUIS0iAP/51-visualizations-of-metabolism-estimates now, but I do see what you mean

**Comment by aappling-usgs** [comment]
cool. note for whoever ends up handling this issue: there's an example of applying combine_ts in mda.streams::config_to_data. data are loaded here: https://github.com/USGS-R/mda.streams/blob/master/R/config_to_data.R#L70 and combined here: https://github.com/USGS-R/mda.streams/blob/master/R/config_to_data.R#L100

**Comment by aappling-usgs** [comment]
fixed in mda.streams as get_ts
