### ISSUE TITLE
usability feedback

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/powstreams#46]
initial feedback:
* would like an easier way to close the GUIs - difficulty with R text editor/console. escape works.
* would be helpful to have % sat: doobs/dosat
* would like to be able to select streams by name. maybe have a code with stream name/state
* could put a map in the lower left for explore_timeseries

@robohall (and others - @tedstets-usgs?), please feel free to add additional feedback on the powstreams user interface here.

**Comment by aappling-usgs** [comment]
initial feedback from @tedstets-usgs:
* some summary statistics for the metabolism estimates would be nice. 'things like median r, p, k, monthly averages, etc.... something that could collapse down into a relatively small number of values as a way of comparing between sites.'

**Comment by jread-usgs** [comment]
got most of these
