### ISSUE TITLE
check legend colors in explore_map

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/powstreams#53]
I'm looking at `dvqcoefs.c` in `explore_map`. The range of values is 0 to 2.5 in both the histogram and the legend, but the histogram indicates there should only be a couple of values in the 2-2.5 range, while the map shows lots of deep maroon points. Hovering over those points confirms that their values are often in the 0.5-1.5 range, despite their deep maroonness. Seems like the points coloring might not be properly aligned with the values and/or the color legend...take a look, @jread-usgs ?

**Comment by jread-usgs** [comment]
got a fix for this.

**Comment by aappling-usgs** [comment]
:+1:
